mysite/urls.py
from django.contrib import admin
from django.urls import path
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('product_add/', views.product_add, name='product_add'),
    path('cart_home/', views.cart_home, name='cart_home'),
    path('cart_update/', views.cart_update, name='cart_update'),
    path('product_detail/<slug:slug>/', views.product_detail, name='product_detail'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('checkout_home/', views.checkout_home, name='checkout_home'),

]

blog/models.py
import math
from math import fsum
from django.db import models
from django.db.models import Manager
from django.db.models.signals import m2m_changed, pre_save, post_save
from django.utils.text import slugify
# User = settings.AUTH_USER_MODEL
from django.conf import settings
from .utils import unique_order_id_generator
from django.db.models import signals


class Category(models.Model):
    objects = None
    id = models.AutoField(primary_key=True)
    category = models.CharField(max_length=50)
    slug = models.SlugField(unique=True, null=False, blank=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.category)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.category


class Attribute(models.Model):
    objects = None
    id = models.AutoField(primary_key=True)
    atribute = models.CharField(unique=True, max_length=20)
    slug = models.SlugField(unique=True, null=False, blank=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.atribute)
        super(Attribute, self).save(*args, **kwargs)

    def __str__(self):
        return self.atribute


class Configure(models.Model):
    objects = None
    id = models.AutoField(primary_key=True)
    configure = models.CharField(max_length=50)
    attribute = models.ForeignKey(Attribute, on_delete=models.CASCADE, null=True, blank=True, )
    slug = models.SlugField(unique=True, null=False, blank=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.configure)
        super(Configure, self).save(*args, **kwargs)

    def __str__(self):
        return self.configure


class Product(models.Model):
    objects = None
    id = models.AutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=255, db_index=True, default='')
    price = models.IntegerField(blank=True, null=True)
    main_image = models.ImageField(upload_to='media/products')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    attribute = models.ForeignKey(Attribute, on_delete=models.SET_NULL, null=True, blank=True)
    configure = models.ForeignKey(Configure, on_delete=models.SET_NULL, null=True, blank=True)
    slug = models.SlugField(unique=True, null=False, blank=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    # @property
    # def name(self):
    #     return self.name


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    # objects = None
    objects = CartManager()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    update = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        print(action)
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()
        print(total)


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = float(instance.subtotal) + float(10)    #10 rs for delivery charges
    else:
        instance.total = 0.00


pre_save.connect(pre_save_cart_receiver, sender=Cart)


class Order(models.Model):
    objects = None
    object = None
    ORDER_STATUS_CHOICE = (
        ('created', 'created'),
        ('paid','paid'),
        ('shipped', 'shipped'),
        ('refunded', 'refunded'),
    )
    order_id = models.CharField(max_length=120, blank=True)
    # billing_profile =
    # shipping_address =
    # billing_address =
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE,)
    status = models.CharField(max_length=120, default='created', choices= ORDER_STATUS_CHOICE)
    shipping_total = models.DecimalField(default=10, max_digits=100, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)

    def __str__(self):
        return str(self.order_id)

    def update_total(self):
        cart_total = self.cart.total
        shipping_total = self.shipping_total
        new_total = math.fsum([cart_total + shipping_total])
        formatted_total = format(new_total, '.2f')
        self.total = new_total
        self.save()
        return new_total


def pre_save_create_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = unique_order_id_generator(instance)


pre_save.connect(pre_save_create_order_id, sender=Order)


def post_save_cart_total(sender, instance, created, *args, **kwargs):
    if not created:
        cart_obj = instance
        cart_total = cart_obj.total
        cart_id = cart_obj.id
        qs = Order.objects.filter(cart_id=cart_id)
        if qs.count() == 1:
            order_obj = qs.first()
            order_obj.update_total()


post_save.connect(post_save_cart_total, sender=Cart)


def post_save_cart_total(sender, instance, created, *args, **kwargs):
    print("running")
    if created:
        print("updating")
        instance.update_total()


post_save.connect(post_save_cart_total, sender=Order)

blog/forms.py
from django import forms
from .models import Product, Category, Configure, Attribute


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'price', 'main_image', 'category', 'attribute', 'configure')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['configure'].queryset = Configure.objects.none()

        if 'attribute' in self.data:
            try:
                attribute_id = int(self.data.get('attribute'))
                self.fields['configure'].queryset = Configure.objects.filter(attribute__id=attribute_id).order_by(
                    'slug')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['configure'].queryset = self.instance.attribute.configure_set.order_by('slug')

blog/views.py
from urllib import request

from django.http import Http404
from django.views.generic import DetailView

from .models import Product, Category, Configure, Attribute, Cart, CartManager, Order
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ProductForm


def index(request):
    return render(request, 'index.html')


def product_add(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            print("11111111111")
            product = form.save(commit=False)
            product.save()
            return redirect('index')
    else:
        form = ProductForm()
    allproducts = Product.objects.filter()
    allsubcategory = Category.objects.filter()
    allattribute = Attribute.objects.filter()
    allconfigure = Configure.objects.filter()
    return render(request, 'product.html', locals())


def product_detail(request, slug):
    product= get_object_or_404(Product, slug=slug)
    return render(request,'product_detail.html', locals())

# def load_cities(request):
#     country_id = request.GET.get('country')
#     cities = City.objects.filter(country_id=country_id).order_by('name')
#     return render(request, 'city_dropdown_list_options.html', {'cities': cities})


def load_cities(request):
    # attribute_id = request.GET.get('id_attribute')   #attribute_id_list
    attribute_id = request.GET['attribute']
    print(attribute_id, '2222222')
    configures = Configure.objects.filter(attribute_id=attribute_id).order_by('slug')
    print(configures, "7777777777777")
    return render(request, 'city_dropdown_list_options.html', {'configures': configures})


# def cart_create(user=None):
#     cart_obj = Cart.objects.create(user=None)
#     print("new cart created")
#     return (cart_obj)


# class ProductDetailSlugView(DetailView):
#     queryset = Product.objects.all()
#     template_name = "product_detail.html"
#
#     def get_context_data(self, *args, **kwargs):
#         context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
#         cart_obj, new_obj = Cart.objects.new_or_get(self.request)
#         context['cart'] = cart_obj
#         return context
#
#     def get_object(self, *args, **kwargs):
#         request = self.request
#         slug = self.kwargs.get('slug')
#     try:
#         instance = Product.objects.get(slug=slug, active=True)
#     except Product.DoesNotExist:
#         raise Http404("Not Found")
#     except Product.MultipleObjectsReturend:
#         qs = Product.objects.filter(slug=slug, active=True)
#         instance = qs.first()
#     except:
#         raise Http404("ummmm")
#     return instance


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    # print(request.session, '@@@@')
    # key=request.session.session_key
    # print(key, '$$$$')
    # print(request.session.get('username', 'unknown'))
    return render(request, 'cart.html', locals())


# def cart_update(request):
#     print(request.POST)
#     product_id = request.POST.get('product_id')
#     if product_id is None:
#         try:
#             product_obj = Product.objects.get(id=product_id)
#         except Product.DoesNotExist:
#             print("Show message to user product is gone")
#             return redirect('index')
#         cart_obj, new_obj = Cart.objects.new_or_get(request)
#         if product_obj in cart_obj.products.all():
#             cart_obj.products.remove(product_obj)   # use to remove m2m products field
#         else:
#             cart_obj.products.add(product_obj)  # cart_obj.products.add(product_id)   # use to add m2m products field
#     # return redirect(product_obj.get_absolute_url())
#     return redirect('index')


def cart_update(request):
    print(request.POST)
    product_id = request.POST.get('product_id')
    product_obj = Product.objects.get(id=product_id)
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    if product_obj in cart_obj.products.all():
        cart_obj.products.remove(product_obj)   # use to remove m2m products field
    else:
        cart_obj.products.add(product_obj)  # use to add m2m products field
    request.session['cart_items'] = cart_obj.products.count()
    # return redirect(product_obj.get_absolute_url())
    return redirect('cart_home')


def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if not cart_created or cart_obj.count() == 0:
        return redirect('index')
    else:
        order_obj, new_order_obj = Order.objects.get_or_create(cart=cart_obj)
    return render(request, "checkout.html", locals())

blog/templates/base.html
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Simple DEMO{% endblock %}</title>
    <style type="text/css">
      .errorlist {
        margin: 0;
        padding: 0;
      }
      .errorlist li {
        list-style: none;
        font-size: 90%;
        color: red;
      }
      .errorlist ~ input,
      .errorlist ~ select {
        border-color: red;
      }
    </style>
  </head>
  <body>
    <h1>Simple DEMO</h1>
    <a href="{% url 'index' %}">home</a>
     <a href="{% url 'product_add' %}">product</a>
     <a href="{% url 'cart_home' %}">{{request.session.cart_items}} cart</a>
     <a href="{%  url 'checkout_home' %}">checkout</a>
    <hr>
    {% block content %}
    {% endblock %}
  </body>
</html>

blog/templates/cart.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<h4>Cart List</h4>

{% if cart_obj.products.exists %}

<table>
   <thead>
   <tr>
      <th>Serial No</th>
      <th>Name</th>
      <th>Price</th>
      <th>remove / add</th>
   </tr>
   </thead>
   <tbody>
   <tr>
      {% for product in cart_obj.products.all %}
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'product_detail' product.slug  %}">{{ product.name }}</a></td>
            <td>{{ product.price }}</td>
            <td>
<!--                <form method="POST" action="{% url 'cart_update' %}">-->
<!--                    {% csrf_token %}-->
<!--                    <input type="hidden" name="product_id" value="{{product.id}}">-->
<!--                        {% if product in Cart.objects.all %}-->

<!--                        {% else %}-->
<!--                          <button type="submit">Remove</button>-->
<!--                        {% endif %}-->
<!--                </form>-->



                <form method="POST" action="{% url 'cart_update' %}">
                    {% csrf_token %}
                    <input type="hidden" name="product_id" value="{{product.id}}">
                    {% if in_cart == True %}
<!--                            <button type="submit">1Remove</button>-->
                    {% else %}
                        {% if product in Cart.objects.all %}
<!--                                <button type="submit">2Remove</button>-->
                        {% else %}
                          <button type="submit">3Remove</button>   <!--<button type="submit">add to cart</button>-->
                        {% endif %}
                    {% endif %}
                </form>
            </td>
      {% endfor %}
   </tr>
   <tr><td> <a href="{%  url 'checkout_home' %}">checkout</a></td></tr>
   </tbody>
</table>

<p>Sub total: {{cart_obj.subtotal}}</p>
   <p>total: {{cart_obj.total}}</p>

{% else %}

<p>cart is empty</p>

{% endif %}

{% endblock %}

blog/templates/checkout.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<h4>Checkout</h4>

cart total: {{object.cart.total}}
sub total: {{object.shipping_total}}
order total: {{object.total}}

{% endblock %}

blog/templates/city_dropdown_list_options.html
<option value="">---------</option>
{% for con in configures %}
<option value="{{ con.id }}">{{ con.configure }}</option>
{% endfor %}

blog/templates/index.html
{% extends 'base.html' %}

{% load static %}
{% block content %}


<!-- main section -->

    <h4>Index Page</h4>
    <a href="{% url 'product_add' %}">product list</a>
    <br>
     <a href="{% url 'cart_home' %}">CArt</a>
    <br>


    {% endblock %}

blog/templates/product.html
{% extends 'base.html' %}

{% load static %}
{% block content %}


<!-- main section -->
    <h4>Product List</h4>
<br>
                        {% for pro in allproducts %}
                            {{pro.name}}
                            {{pro.price}}
<a href="{% url 'product_detail' pro.slug %}" >product detail</a>
<!--<a href="{% url 'cart_home' %}" >add to cart</a>-->
    <br>
                        {% endfor %}


<!-- add new product  -->

                <h5 class="modal-title">Add New Product</h5>
                <br>

    <form method="post" enctype="multipart/form-data"  id="personForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
    {% csrf_token %}
      {{ form.as_p }}


<!--        <div class="form-group col-md-12">-->
<!--            <label> name</label>-->
<!--            <input type="text" class="form-control" name="name" placeholder="" />-->
<!--        </div>-->
<!--        <div class="form-group col-md-12">-->
<!--            <label>price</label>-->
<!--            <input type="text" class="form-control" name="price" placeholder="" />-->
<!--        </div>-->
<!--        <div class="form-group col-md-12">-->
<!--               <label>Image</label>-->
<!--               <input type="file" class="form-control image-upload" name="main_image" />-->
<!--        </div>-->
<!--        <div class="form-group col-md-12">-->
<!--                        <label>Category</label>-->
<!--                        <select class="custom-select" name="category">-->
<!--                            <option selected>Open this select menu</option>-->
<!--                            {% for sub in allsubcategory %}-->
<!--                            <option value="{{sub.id}}">{{ sub.subcategoryname }}</option>-->
<!--                            {% endfor %}-->
<!--                        </select>-->
<!--        </div>-->
<!--        <div class="form-group col-md-12">-->
<!--                        <label>Attribute</label>-->
<!--                        <select class="custom-select" name="attribute" id="id_attribute">-->
<!--                            <option selected>Open this select menu</option>-->
<!--                           {% for attr in allattribute %}-->
<!--                            <option value="{{attr.id}}">{{ attr.atributesname }}</option>-->
<!--                            {% endfor %}-->
<!--                        </select>-->
<!--        </div>-->
<!--        <div class="form-group col-md-12">-->
<!--                        <label>Configure</label>-->
<!--                        <select class="custom-select" name="configure" id="id_configure">-->
<!--                            <option selected>Open this select menu</option>-->
<!--                            {% for conf in allconfigure %}-->
<!--                            <option value="{{conf.id}}">{{ conf.configuresname }}</option>-->
<!--                            {% endfor %}-->
<!--                        </select>-->
<!--        </div>-->


    <button type="submit">Save</button>
  </form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>




  <script>
    $("#id_attribute").change(function () {
<!--    console.log("hhhhhhhhhhhhhhh");-->
      var url = $("#personForm").attr("data-cities-url");
      var attributeId = $(this).val();
<!--      console.log(configureId);-->

      $.ajax({
        url: url,
        data: {
          attribute : attributeId
        },
        success: function (data) {
          $("#id_configure").html(data);
<!--          alert("ggggggggggggggggg");-->
        }
      });
    });

  </script>


    {% endblock %}

blog/templates/product_detail.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<h3>Product Detail</h3>

<img src="/media/products/{{product.main_image}}"/>

    {{product.id}}
    {{product.name}}
    {{product.price}}
<br>

<form method="POST" action="{% url 'cart_update' %}">
    {% csrf_token %}
    <input name="product_id" value="{{product.id}}">   <!-- type="hidden" -->
    {% if product in Cart.objects.all %}
        <button type="submit">Remove</button>
    {% else %}
        <button type="submit">add to cart</button>
    {% endif %}
</form>

{% endblock %}